[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base="dark"
primaryColor="#00ff9d"
backgroundColor="#020617"
secondaryBackgroundColor="#0f172a"
textColor="#ffffff"

[theme.sidebar]
widgetBorderColor="#1e293b"
skeletonBackgroundColor="#1e293b"
widgetBackgroundColor="#0f172a"